# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: TheLab Release

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - xsd/**
      - xsd-final/**
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - xsd/**
      - xsd-final/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: get-time
      id: get-time
      run: | 
        version=$(date +'%Y%d%m-%H%M%S')
        echo $version > version.txt
        echo "::set-output name=version::$version"

    - name: get-commit-version
      id: get-commit-version
      run: | 
        commit=$(git log --format="%h" -n 1)
        echo $commit > commit.txt
        echo "::set-output name=commit::$commit"

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn clean package -e "-Dnfs.core.stage=production"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Core-thorntail-reloaded
        path: |
              ${{ github.workspace }}/target/core-thorntail.jar

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get-time.outputs.version }}
        release_name: SBRWReloaded — v ${{ steps.get-time.outputs.version }}
        draft: false
        prerelease: false

    - name: Create upload URL file
      env:
        UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
      run: | 
        echo $UPLOAD_URL > upload-url.txt
        echo "::set-output name=upload-url::$upload_url"

    - name: Upload release's upload URL
      uses: actions/upload-artifact@v2
      with:
        name: upload-url
        path: upload-url.txt

    - name: Create release ID file
      env:
        RELEASE_ID: ${{ steps.create_release.outputs.id }}
      run: echo $RELEASE_ID > release-id.txt

    - name: Upload release's upload URL
      uses: actions/upload-artifact@v2
      with:
        name: release-id
        path: release-id.txt

    - name: Download URL to upload to
      uses: actions/download-artifact@v2
      with:
        name: upload-url
        
    - name: Set output for upload-url
      id: set_upload_url
      run: |
        upload_url=$(tail upload-url.txt)
        echo "::set-output name=upload-url::$upload_url"

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.set_upload_url.outputs.upload-url }}
        asset_path: ${{ github.workspace }}/target/core-thorntail.jar
        asset_name: TheLab-${{ steps.get-commit-version.outputs.commit }}.jar
        asset_content_type: application/octet-stream
